### ISSUE TITLE
Change the logo alignment into right.

### ISSUE THREAD

**Issue by indrapermana** [msioen/WiXBootstrapperLayoutExample#1]
Hi, @msioen What if i want to change the logofile alignment into right? Is there any align tag in WixStandardBootstrapperApplication ? 

Thanks

**Comment by msioen** [comment]
All the layouting/alignment uses absolute coordinates. So you can play with the x/y and width/height coordinates of the elements.
By using positive/negative numbers you change where you start counting from. ie a positive number will start from the left or the top, a negative number starts from the right or the bottom.

Specifically if you would want to change the logofile to the right you'd update the x to a negative margin. The positioning of the text element also will need to be updated to avoid overlap.

https://github.com/msioen/WiXBootstrapperLayoutExample/blob/master/MyProject.Bootstrapper/res/MyCustomBootstrapperTheme.xml#L13-L14

**Comment by indrapermana** [comment]
Oh I see. Thanks @msioen .
